// flow-typed signature: 413092033c5e0bfd660a984fa8ed0e78
// flow-typed version: <<STUB>>/babel-plugin-sitrep_v^1.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-sitrep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-sitrep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-sitrep/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'babel-plugin-sitrep/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'babel-plugin-sitrep/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-sitrep/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-sitrep/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'babel-plugin-sitrep/coverage/lcov-report/prettify'>;
}
declare module 'babel-plugin-sitrep/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'babel-plugin-sitrep/coverage/lcov-report/sorter'>;
}
declare module 'babel-plugin-sitrep/src/__tests__/index.js' {
  declare module.exports: $Exports<'babel-plugin-sitrep/src/__tests__/index'>;
}
declare module 'babel-plugin-sitrep/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-sitrep/src/index'>;
}
