// flow-typed signature: 5d35d44572b9d2b89f178befaa7e12a3
// flow-typed version: <<STUB>>/crosstab_v^0.2.12/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crosstab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crosstab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crosstab/Gruntfile' {
  declare module.exports: any;
}

declare module 'crosstab/sauceconnect' {
  declare module.exports: any;
}

declare module 'crosstab/src/crosstab' {
  declare module.exports: any;
}

declare module 'crosstab/test/browsers' {
  declare module.exports: any;
}

declare module 'crosstab/test/test-crosstab' {
  declare module.exports: any;
}

declare module 'crosstab/typings/expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crosstab/Gruntfile.js' {
  declare module.exports: $Exports<'crosstab/Gruntfile'>;
}
declare module 'crosstab/sauceconnect.js' {
  declare module.exports: $Exports<'crosstab/sauceconnect'>;
}
declare module 'crosstab/src/crosstab.js' {
  declare module.exports: $Exports<'crosstab/src/crosstab'>;
}
declare module 'crosstab/test/browsers.js' {
  declare module.exports: $Exports<'crosstab/test/browsers'>;
}
declare module 'crosstab/test/test-crosstab.js' {
  declare module.exports: $Exports<'crosstab/test/test-crosstab'>;
}
declare module 'crosstab/typings/expect.js' {
  declare module.exports: $Exports<'crosstab/typings/expect'>;
}
