// flow-typed signature: 0b689c0b72cdf4e6c8ae96158f146453
// flow-typed version: <<STUB>>/dooty_v^1.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dooty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dooty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dooty/index' {
  declare module.exports: $Exports<'dooty'>;
}
declare module 'dooty/index.js' {
  declare module.exports: $Exports<'dooty'>;
}
