// flow-typed signature: f3aa5f45c7a107e57f01382125b9764c
// flow-typed version: <<STUB>>/@shiftio/mediasilo-javascript-sdk_v^2.7.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shiftio/mediasilo-javascript-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shiftio/mediasilo-javascript-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shiftio/mediasilo-javascript-sdk/__test_utils__/testSetup' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/account' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/accountPreferences' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/assets' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/contacts' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/feed' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/folders' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/index' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/account' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/accountPreferences' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/assets' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/contacts' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/feed' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/folders' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/projects' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/quicklinks' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/roletemplates' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/sdk' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/sessions' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/shares' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/users' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/projects' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/quicklinks' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/roletemplates' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/sessions' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/shares' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/users' {
  declare module.exports: any;
}

declare module '@shiftio/mediasilo-javascript-sdk/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shiftio/mediasilo-javascript-sdk/__test_utils__/testSetup.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/__test_utils__/testSetup'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/account.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/account'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/accountPreferences.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/accountPreferences'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/assets.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/assets'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/contacts.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/contacts'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/feed.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/feed'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/folders.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/folders'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/index.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/index'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/account.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/account'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/accountPreferences.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/accountPreferences'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/assets.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/assets'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/contacts.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/contacts'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/feed.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/feed'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/folders.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/folders'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/projects.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/projects'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/quicklinks.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/quicklinks'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/roletemplates.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/roletemplates'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/sdk.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/sdk'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/sessions.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/sessions'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/shares.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/shares'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/interfaces/users.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/interfaces/users'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/projects.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/projects'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/quicklinks.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/quicklinks'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/roletemplates.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/roletemplates'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/sessions.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/sessions'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/shares.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/shares'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/users.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/users'>;
}
declare module '@shiftio/mediasilo-javascript-sdk/dist/utils.js' {
  declare module.exports: $Exports<'@shiftio/mediasilo-javascript-sdk/dist/utils'>;
}
