// flow-typed signature: 2221f8278aee54186cdb1c02ef02e829
// flow-typed version: <<STUB>>/@shiftio/player_v^1.22.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shiftio/player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shiftio/player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shiftio/player/dist/bundle' {
  declare module.exports: any;
}

declare module '@shiftio/player/dist/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/App/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/App/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/Button/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/Button/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/Readout/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/Readout/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/Scrubber/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/Scrubber/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/Speed/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Controls/Speed/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Failure/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Failure/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Overlay/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Overlay/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Overlay/Play/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Overlay/Play/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Overlay/Replay/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Overlay/Replay/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Overlay/Wait/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Overlay/Wait/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Video/component' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/components/Video/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/config' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/index' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/analytics' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/captions' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/compatibility' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/format' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/fullscreen' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/helpers' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/jwplayer' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/language' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/native' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/player' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/promise' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/utils/url' {
  declare module.exports: any;
}

declare module '@shiftio/player/src/Vendors' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shiftio/player/dist/bundle.js' {
  declare module.exports: $Exports<'@shiftio/player/dist/bundle'>;
}
declare module '@shiftio/player/dist/index.js' {
  declare module.exports: $Exports<'@shiftio/player/dist/index'>;
}
declare module '@shiftio/player/src/components/App/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/App/component'>;
}
declare module '@shiftio/player/src/components/App/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/App/index'>;
}
declare module '@shiftio/player/src/components/Controls/Button/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/Button/component'>;
}
declare module '@shiftio/player/src/components/Controls/Button/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/Button/index'>;
}
declare module '@shiftio/player/src/components/Controls/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/component'>;
}
declare module '@shiftio/player/src/components/Controls/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/index'>;
}
declare module '@shiftio/player/src/components/Controls/Readout/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/Readout/component'>;
}
declare module '@shiftio/player/src/components/Controls/Readout/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/Readout/index'>;
}
declare module '@shiftio/player/src/components/Controls/Scrubber/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/Scrubber/component'>;
}
declare module '@shiftio/player/src/components/Controls/Scrubber/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/Scrubber/index'>;
}
declare module '@shiftio/player/src/components/Controls/Speed/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/Speed/component'>;
}
declare module '@shiftio/player/src/components/Controls/Speed/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Controls/Speed/index'>;
}
declare module '@shiftio/player/src/components/Failure/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Failure/component'>;
}
declare module '@shiftio/player/src/components/Failure/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Failure/index'>;
}
declare module '@shiftio/player/src/components/Overlay/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Overlay/component'>;
}
declare module '@shiftio/player/src/components/Overlay/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Overlay/index'>;
}
declare module '@shiftio/player/src/components/Overlay/Play/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Overlay/Play/component'>;
}
declare module '@shiftio/player/src/components/Overlay/Play/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Overlay/Play/index'>;
}
declare module '@shiftio/player/src/components/Overlay/Replay/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Overlay/Replay/component'>;
}
declare module '@shiftio/player/src/components/Overlay/Replay/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Overlay/Replay/index'>;
}
declare module '@shiftio/player/src/components/Overlay/Wait/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Overlay/Wait/component'>;
}
declare module '@shiftio/player/src/components/Overlay/Wait/index.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Overlay/Wait/index'>;
}
declare module '@shiftio/player/src/components/Video/component.jsx' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Video/component'>;
}
declare module '@shiftio/player/src/components/Video/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/components/Video/index'>;
}
declare module '@shiftio/player/src/config.js' {
  declare module.exports: $Exports<'@shiftio/player/src/config'>;
}
declare module '@shiftio/player/src/index.js' {
  declare module.exports: $Exports<'@shiftio/player/src/index'>;
}
declare module '@shiftio/player/src/utils/analytics.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/analytics'>;
}
declare module '@shiftio/player/src/utils/captions.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/captions'>;
}
declare module '@shiftio/player/src/utils/compatibility.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/compatibility'>;
}
declare module '@shiftio/player/src/utils/format.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/format'>;
}
declare module '@shiftio/player/src/utils/fullscreen.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/fullscreen'>;
}
declare module '@shiftio/player/src/utils/helpers.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/helpers'>;
}
declare module '@shiftio/player/src/utils/jwplayer.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/jwplayer'>;
}
declare module '@shiftio/player/src/utils/language.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/language'>;
}
declare module '@shiftio/player/src/utils/native.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/native'>;
}
declare module '@shiftio/player/src/utils/player.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/player'>;
}
declare module '@shiftio/player/src/utils/promise.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/promise'>;
}
declare module '@shiftio/player/src/utils/url.js' {
  declare module.exports: $Exports<'@shiftio/player/src/utils/url'>;
}
declare module '@shiftio/player/src/Vendors.js' {
  declare module.exports: $Exports<'@shiftio/player/src/Vendors'>;
}
