// flow-typed signature: c09bfbae0b5db22190799983e3000c44
// flow-typed version: <<STUB>>/@shiftio/shift-icons_v^1.7.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shiftio/shift-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shiftio/shift-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shiftio/shift-icons/dist/app' {
  declare module.exports: any;
}

declare module '@shiftio/shift-icons/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shiftio/shift-icons/dist/app.js' {
  declare module.exports: $Exports<'@shiftio/shift-icons/dist/app'>;
}
declare module '@shiftio/shift-icons/dist/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-icons/dist/index'>;
}
