// flow-typed signature: 68299c24b4885d2e38a0080f041a04af
// flow-typed version: <<STUB>>/@shiftio/shift-patterns_v^12.5.8/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shiftio/shift-patterns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shiftio/shift-patterns' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shiftio/shift-patterns/dist/atoms/Aspectbox/Aspectbox' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Aspectbox/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/AspectRatioContainer/AspectRatioContainer' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/AspectRatioContainer/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/AudioWaveform/AudioWaveform' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/AudioWaveform/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/AudioWaveform/waveform' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Avatar/Avatar' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Avatar/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Button/Button' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Button/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Canvas/Canvas' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Canvas/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Card/Card' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Card/Card.stories' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Card/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Carousel/Carousel' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Carousel/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Checkbox/Checkbox' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Checkbox/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/ColorPicker/ColorPicker' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/ColorPicker/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/colors' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Column/Column' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Column/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/ContextMenu/ContextMenu' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/ContextMenu/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Document/Document' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Document/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Download/Download' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Download/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Dropdown/Dropdown' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Dropdown/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/EditorInput/EditorInput' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/EditorInput/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Ellipsis/Ellipsis' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Ellipsis/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/FileDropzone/FileDropzone' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/FileDropzone/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Fitbox/Fitbox' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Fitbox/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Flyout/Flyout' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Flyout/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Folder/Folder' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Folder/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Form/Form' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Form/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/IconMenu/IconMenu' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/IconMenu/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/IndeterminateLoader/IndeterminateLoader' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/IndeterminateLoader/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Input/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Input/Input' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Input/Tip' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Label/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Label/Label' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Loader/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Loader/Loader' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Menu/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Menu/Menu' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Modal/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Modal/Modal' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Modal/ModalHeader' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Modal/ModalSections' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Modal/ModalTabOption' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Modal/ModalTabs' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/ModalSections/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/ModalSections/ModalSections' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/MouseMenu/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/MouseMenu/MouseMenu' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Overlay/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Overlay/Overlay' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/PageTitle/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/PageTitle/PageTitle' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/PageTitle/PageTitle.stories' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Popover/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Popover/Popover' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Portal/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Portal/Portal' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/PreviewImage/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/PreviewImage/PreviewImage' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Row/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Row/Row' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Select/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Select/Select' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Skidoodle/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidaddle' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidoodle' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidoodle.stories' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Switch/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Switch/Switch' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Tags/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Tags/TagItem' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Tags/Tags' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Textarea/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Textarea/Textarea' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Time/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/Time/Time' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/WindowEventProvider/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/atoms/WindowEventProvider/WindowEventProvider' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/defaultTheme' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/exampleComponents/Component' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/exampleComponents/StatelessComponent' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/helpers/WithHover' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Asset/Asset' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Asset/Asset.stories' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Asset/AssetThumbnail/AssetThumbnail' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Asset/AssetThumbnail/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Asset/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/AssetPlaceholder/AssetPlaceholder' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/AssetPlaceholder/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Comment/Comment' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Comment/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/createScrollable/animations' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/createScrollable/createScrollable' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/createScrollable/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/createSelectable/createSelectable' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/createSelectable/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/createUnselectable/createUnselectable' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/createUnselectable/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/JWPlayer/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/JWPlayer/JWPlayer' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Masonry/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Masonry/Masonry' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Modal/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Modal/Modal' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Project/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Project/Project' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Scrollable/animations' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Scrollable/createScrollable' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Scrollable/ScrollContainer' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/Scrollable/ScrollContainer.stories' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/ScrollContainer/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/ScrollContainer/ScrollContainer' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/ScrollContainer/ScrollContainer.stories' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/selectable/createSelectable' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/selectable/createUnselectable' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/selectable/Lasso/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/selectable/Lasso/Lasso' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/selectable/SelectableGroup' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/selectable/utils' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/SelectableGroup/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/SelectableGroup/SelectableGroup' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/SelectableGroup/SelectableGroup.stories' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/SelectableGroup/utils' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/ThumbnailScrubber/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/ThumbnailScrubber/ThumbnailScrubber' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/VirtualizedFeed/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/molecules/VirtualizedFeed/VirtualizedFeed' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/PlaygroundWrapper' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/Theme/Themeable' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/Theme/ThemeProvider' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/dist/utils' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/jwplayer' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.base64' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.promise' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.vttrenderer' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.cast' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.caterpillar' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.flash' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.html5' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.shaka' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.youtube' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/vttparser' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/scripts/resolve' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/src/types/cssStub' {
  declare module.exports: any;
}

declare module '@shiftio/shift-patterns/src/types/user' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shiftio/shift-patterns/dist/atoms/Aspectbox/Aspectbox.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Aspectbox/Aspectbox'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Aspectbox/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Aspectbox/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/AspectRatioContainer/AspectRatioContainer.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/AspectRatioContainer/AspectRatioContainer'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/AspectRatioContainer/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/AspectRatioContainer/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/AudioWaveform/AudioWaveform.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/AudioWaveform/AudioWaveform'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/AudioWaveform/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/AudioWaveform/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/AudioWaveform/waveform.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/AudioWaveform/waveform'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Avatar/Avatar.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Avatar/Avatar'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Avatar/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Avatar/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Button/Button.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Button/Button'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Button/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Button/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Canvas/Canvas.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Canvas/Canvas'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Canvas/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Canvas/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Card/Card.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Card/Card'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Card/Card.stories.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Card/Card.stories'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Card/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Card/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Carousel/Carousel.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Carousel/Carousel'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Carousel/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Carousel/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Checkbox/Checkbox.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Checkbox/Checkbox'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Checkbox/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Checkbox/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/ColorPicker/ColorPicker.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/ColorPicker/ColorPicker'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/ColorPicker/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/ColorPicker/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/colors.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/colors'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Column/Column.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Column/Column'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Column/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Column/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/ContextMenu/ContextMenu.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/ContextMenu/ContextMenu'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/ContextMenu/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/ContextMenu/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Document/Document.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Document/Document'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Document/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Document/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Download/Download.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Download/Download'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Download/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Download/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Dropdown/Dropdown.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Dropdown/Dropdown'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Dropdown/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Dropdown/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/EditorInput/EditorInput.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/EditorInput/EditorInput'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/EditorInput/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/EditorInput/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Ellipsis/Ellipsis.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Ellipsis/Ellipsis'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Ellipsis/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Ellipsis/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/FileDropzone/FileDropzone.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/FileDropzone/FileDropzone'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/FileDropzone/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/FileDropzone/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Fitbox/Fitbox.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Fitbox/Fitbox'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Fitbox/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Fitbox/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Flyout/Flyout.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Flyout/Flyout'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Flyout/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Flyout/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Folder/Folder.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Folder/Folder'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Folder/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Folder/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Form/Form.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Form/Form'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Form/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Form/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/IconMenu/IconMenu.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/IconMenu/IconMenu'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/IconMenu/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/IconMenu/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/IndeterminateLoader/IndeterminateLoader.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/IndeterminateLoader/IndeterminateLoader'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/IndeterminateLoader/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/IndeterminateLoader/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Input/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Input/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Input/Input.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Input/Input'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Input/Tip.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Input/Tip'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Label/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Label/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Label/Label.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Label/Label'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Loader/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Loader/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Loader/Loader.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Loader/Loader'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Menu/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Menu/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Menu/Menu.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Menu/Menu'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Modal/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Modal/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Modal/Modal.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Modal/Modal'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Modal/ModalHeader.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Modal/ModalHeader'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Modal/ModalSections.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Modal/ModalSections'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Modal/ModalTabOption.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Modal/ModalTabOption'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Modal/ModalTabs.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Modal/ModalTabs'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/ModalSections/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/ModalSections/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/ModalSections/ModalSections.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/ModalSections/ModalSections'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/MouseMenu/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/MouseMenu/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/MouseMenu/MouseMenu.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/MouseMenu/MouseMenu'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Overlay/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Overlay/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Overlay/Overlay.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Overlay/Overlay'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/PageTitle/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/PageTitle/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/PageTitle/PageTitle.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/PageTitle/PageTitle'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/PageTitle/PageTitle.stories.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/PageTitle/PageTitle.stories'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Popover/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Popover/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Popover/Popover.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Popover/Popover'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Portal/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Portal/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Portal/Portal.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Portal/Portal'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/PreviewImage/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/PreviewImage/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/PreviewImage/PreviewImage.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/PreviewImage/PreviewImage'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Row/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Row/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Row/Row.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Row/Row'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Select/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Select/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Select/Select.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Select/Select'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Skidoodle/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Skidoodle/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidaddle.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidaddle'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidoodle.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidoodle'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidoodle.stories.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Skidoodle/Skidoodle.stories'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Switch/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Switch/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Switch/Switch.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Switch/Switch'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Tags/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Tags/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Tags/TagItem.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Tags/TagItem'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Tags/Tags.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Tags/Tags'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Textarea/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Textarea/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Textarea/Textarea.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Textarea/Textarea'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Time/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Time/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/Time/Time.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/Time/Time'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/WindowEventProvider/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/WindowEventProvider/index'>;
}
declare module '@shiftio/shift-patterns/dist/atoms/WindowEventProvider/WindowEventProvider.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/atoms/WindowEventProvider/WindowEventProvider'>;
}
declare module '@shiftio/shift-patterns/dist/defaultTheme.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/defaultTheme'>;
}
declare module '@shiftio/shift-patterns/dist/exampleComponents/Component.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/exampleComponents/Component'>;
}
declare module '@shiftio/shift-patterns/dist/exampleComponents/StatelessComponent.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/exampleComponents/StatelessComponent'>;
}
declare module '@shiftio/shift-patterns/dist/helpers/WithHover.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/helpers/WithHover'>;
}
declare module '@shiftio/shift-patterns/dist/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Asset/Asset.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Asset/Asset'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Asset/Asset.stories.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Asset/Asset.stories'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Asset/AssetThumbnail/AssetThumbnail.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Asset/AssetThumbnail/AssetThumbnail'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Asset/AssetThumbnail/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Asset/AssetThumbnail/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Asset/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Asset/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/AssetPlaceholder/AssetPlaceholder.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/AssetPlaceholder/AssetPlaceholder'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/AssetPlaceholder/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/AssetPlaceholder/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Comment/Comment.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Comment/Comment'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Comment/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Comment/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/createScrollable/animations.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/createScrollable/animations'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/createScrollable/createScrollable.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/createScrollable/createScrollable'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/createScrollable/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/createScrollable/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/createSelectable/createSelectable.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/createSelectable/createSelectable'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/createSelectable/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/createSelectable/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/createUnselectable/createUnselectable.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/createUnselectable/createUnselectable'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/createUnselectable/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/createUnselectable/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/JWPlayer/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/JWPlayer/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/JWPlayer/JWPlayer.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/JWPlayer/JWPlayer'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Masonry/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Masonry/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Masonry/Masonry.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Masonry/Masonry'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Modal/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Modal/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Modal/Modal.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Modal/Modal'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Project/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Project/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Project/Project.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Project/Project'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Scrollable/animations.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Scrollable/animations'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Scrollable/createScrollable.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Scrollable/createScrollable'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Scrollable/ScrollContainer.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Scrollable/ScrollContainer'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/Scrollable/ScrollContainer.stories.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/Scrollable/ScrollContainer.stories'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/ScrollContainer/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/ScrollContainer/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/ScrollContainer/ScrollContainer.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/ScrollContainer/ScrollContainer'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/ScrollContainer/ScrollContainer.stories.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/ScrollContainer/ScrollContainer.stories'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/selectable/createSelectable.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/selectable/createSelectable'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/selectable/createUnselectable.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/selectable/createUnselectable'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/selectable/Lasso/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/selectable/Lasso/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/selectable/Lasso/Lasso.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/selectable/Lasso/Lasso'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/selectable/SelectableGroup.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/selectable/SelectableGroup'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/selectable/utils.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/selectable/utils'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/SelectableGroup/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/SelectableGroup/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/SelectableGroup/SelectableGroup.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/SelectableGroup/SelectableGroup'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/SelectableGroup/SelectableGroup.stories.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/SelectableGroup/SelectableGroup.stories'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/SelectableGroup/utils.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/SelectableGroup/utils'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/ThumbnailScrubber/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/ThumbnailScrubber/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/ThumbnailScrubber/ThumbnailScrubber.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/ThumbnailScrubber/ThumbnailScrubber'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/VirtualizedFeed/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/VirtualizedFeed/index'>;
}
declare module '@shiftio/shift-patterns/dist/molecules/VirtualizedFeed/VirtualizedFeed.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/molecules/VirtualizedFeed/VirtualizedFeed'>;
}
declare module '@shiftio/shift-patterns/dist/PlaygroundWrapper.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/PlaygroundWrapper'>;
}
declare module '@shiftio/shift-patterns/dist/Theme/Themeable.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/Theme/Themeable'>;
}
declare module '@shiftio/shift-patterns/dist/Theme/ThemeProvider.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/Theme/ThemeProvider'>;
}
declare module '@shiftio/shift-patterns/dist/utils.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/dist/utils'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/jwplayer.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/jwplayer'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.base64.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.base64'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.promise.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.promise'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.vttrenderer.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/polyfills.vttrenderer'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.cast.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.cast'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.caterpillar.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.caterpillar'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.flash.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.flash'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.html5.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.html5'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.shaka.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.shaka'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.youtube.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/provider.youtube'>;
}
declare module '@shiftio/shift-patterns/lib/jwplayer-7.7.4/vttparser.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/lib/jwplayer-7.7.4/vttparser'>;
}
declare module '@shiftio/shift-patterns/scripts/resolve.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/scripts/resolve'>;
}
declare module '@shiftio/shift-patterns/src/types/cssStub.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/src/types/cssStub'>;
}
declare module '@shiftio/shift-patterns/src/types/user.js' {
  declare module.exports: $Exports<'@shiftio/shift-patterns/src/types/user'>;
}
