// flow-typed signature: 5fa341cac882af584a877e1f078747dd
// flow-typed version: <<STUB>>/@shiftio/shift-utils_v^0.7.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shiftio/shift-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shiftio/shift-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shiftio/shift-utils/lib/config' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/delay/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/delay/index.test' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/findPath/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/findPath/index.test' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/generatePreviewUrl/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/generatePreviewUrl/index.test' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/index.test' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/prettyBytes/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/prettyBytes/index.test' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/qs/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/qs/index.test' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/uglyBytes/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/uglyBytes/index.test' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/webvtt/index' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/webvtt/webvtt' {
  declare module.exports: any;
}

declare module '@shiftio/shift-utils/lib/webvtt/webvtt.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shiftio/shift-utils/lib/config.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/config'>;
}
declare module '@shiftio/shift-utils/lib/delay/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/delay/index'>;
}
declare module '@shiftio/shift-utils/lib/delay/index.test.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/delay/index.test'>;
}
declare module '@shiftio/shift-utils/lib/findPath/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/findPath/index'>;
}
declare module '@shiftio/shift-utils/lib/findPath/index.test.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/findPath/index.test'>;
}
declare module '@shiftio/shift-utils/lib/generatePreviewUrl/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/generatePreviewUrl/index'>;
}
declare module '@shiftio/shift-utils/lib/generatePreviewUrl/index.test.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/generatePreviewUrl/index.test'>;
}
declare module '@shiftio/shift-utils/lib/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/index'>;
}
declare module '@shiftio/shift-utils/lib/index.test.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/index.test'>;
}
declare module '@shiftio/shift-utils/lib/prettyBytes/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/prettyBytes/index'>;
}
declare module '@shiftio/shift-utils/lib/prettyBytes/index.test.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/prettyBytes/index.test'>;
}
declare module '@shiftio/shift-utils/lib/qs/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/qs/index'>;
}
declare module '@shiftio/shift-utils/lib/qs/index.test.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/qs/index.test'>;
}
declare module '@shiftio/shift-utils/lib/uglyBytes/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/uglyBytes/index'>;
}
declare module '@shiftio/shift-utils/lib/uglyBytes/index.test.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/uglyBytes/index.test'>;
}
declare module '@shiftio/shift-utils/lib/webvtt/index.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/webvtt/index'>;
}
declare module '@shiftio/shift-utils/lib/webvtt/webvtt.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/webvtt/webvtt'>;
}
declare module '@shiftio/shift-utils/lib/webvtt/webvtt.test.js' {
  declare module.exports: $Exports<'@shiftio/shift-utils/lib/webvtt/webvtt.test'>;
}
