// flow-typed signature: 535ba6b1af127e4fcb2bc92e9e0e3eea
// flow-typed version: <<STUB>>/@shiftio/tracking_v^1.3.5/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shiftio/tracking'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shiftio/tracking' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shiftio/tracking/dist/index' {
  declare module.exports: any;
}

declare module '@shiftio/tracking/dist/log' {
  declare module.exports: any;
}

declare module '@shiftio/tracking/src/index' {
  declare module.exports: any;
}

declare module '@shiftio/tracking/src/log' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shiftio/tracking/dist/index.js' {
  declare module.exports: $Exports<'@shiftio/tracking/dist/index'>;
}
declare module '@shiftio/tracking/dist/log.js' {
  declare module.exports: $Exports<'@shiftio/tracking/dist/log'>;
}
declare module '@shiftio/tracking/src/index.js' {
  declare module.exports: $Exports<'@shiftio/tracking/src/index'>;
}
declare module '@shiftio/tracking/src/log.js' {
  declare module.exports: $Exports<'@shiftio/tracking/src/log'>;
}
