import { fooAction } from '../actions';

// Autogenerated tests
describe('fooAction', () => {
  it('should create an action with a type of scope/example', () => {
    expect(fooAction().type).toBe('scope/example');
  });

  it('should set an Error as the payload if called with one', () => {
    const err = new Error('test');
    expect(fooAction(err).payload instanceof Error).toBe(true);
  });

  it('should set an error attribute if called with an Error', () => {
    const err = new Error('test');
    expect(fooAction(err).error).toBe(true);
  });
});
